import { cookies } from "next/headers";
import "./globals.css";
import Link from "next/link";
import { handleClientScriptLoad } from "next/script";
import HeaderAuthButton from "./components/headerAuthLogout";
import AuthGuard from "./providers/AuthGuard";
export const dynamic = "force-dynamic";

const secret = new TextEncoder().encode(process.env.JWT_SECRET)

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {

   const token = cookies().get("token")?.value

   return (
      <html lang="ko">
         <body>
            <div className="navbar">
               <Link href="/" className="logo">Appleforum</Link>
               <Link href="/write">write</Link>
               <Link href="/list">List</Link>
               <div><HeaderAuthButton token={token}/></div>
               <Link href="/signup"style={{marginLeft: "15px"}}>회원가입</Link>

            </div>
            <AuthGuard>
               {children}
            </AuthGuard>
         </body>
      </html>
   );
}
